# Generated by Django 4.1.7 on 2023-04-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('curr', models.CharField(default='HKD', max_length=255)),
                ('remark', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
