# Generated by Django 4.1.7 on 2023-03-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='remark',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
