# Generated by Django 4.1.7 on 2023-04-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='curr',
            field=models.CharField(default='HKD', max_length=255),
        ),
    ]
