# Generated by Django 4.1.7 on 2023-04-07 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr', models.CharField(max_length=5)),
                ('dat', models.DateField(default=datetime.date.today)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=25)),
            ],
        ),
    ]
