# Generated by Django 4.1.7 on 2023-04-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyrecord',
            old_name='dat',
            new_name='date',
        ),
    ]
